### ISSUE TITLE
mainMediaPl can't get EXT-X-KEY

### ISSUE THREAD

**Issue by carruis** [alexsun/M3U8Paser#1]
my m3u8 list have this tag in mainMediaPl
#EXT-X-KEY:METHOD=AES-128,URI="XXXX",IV=XXXX

Can use this parser get URI and IV?

**Comment by wolfcon** [comment]
`We have move this project to` [M3U8Kit](https://github.com/M3U8Kit/M3U8Parser).

Maybe you should parse by yourself, because of EXT-X-Key is not unique. There are more than one X-Key in MainMediaPlaylist.

**Comment by wolfcon** [comment]
`We have move this project to` [M3U8Kit](https://github.com/M3U8Kit/M3U8Parser).
@carruis EXT-X-Key is already supported by M3U8Kit (0.3.0). 
[Check this out](https://github.com/M3U8Kit/M3U8Parser).

**Comment by carruis** [comment]
thank you so much
