### ISSUE TITLE
Blank screen 

### ISSUE THREAD

**Issue by CearsKhush** [alexsun/M3U8Paser#2]
Hello @alexsun, I have just downloaded the demo and try to run it but I am not able to see anything. There is only white screen is appearing 

![Screen Shot 2019-10-21 at 11 21 14 AM](https://user-images.githubusercontent.com/49678377/67179732-e6b98b00-f3f4-11e9-8e62-e70b858d946f.png)

Can you please guide me?

Thank you

**Comment by wolfcon** [comment]
This repo has been transfer to [M3U8Kit](https://github.com/M3U8Kit/M3U8Parser).

You should see console log, or set a breakpoint to see results.
